### ISSUE TITLE
Reset when item is removed

### ISSUE THREAD

**Issue by qtagtech** [mikkokam/NUI#1]
I'm trying to figure out how to implement a functionalit so that if I remove an object from the array of objects, (i.e in demo==3), the rest of the objects re-arrange and it doesn't leave the space as if the recently removed object was still there.

**Comment by mikkokam** [comment]
**EDITED**

Since this is just a proof-of-concept demo, there is no proper API or docs - sorry about that.

Any DOM element using the directive will automatically create a **body** in the physics engine world.
You can remove an item completely by calling destroy for **both** the Angular side visual representation of the object (i.e. the DOM element created by the directive, such as the helper Array is doing via ng-repeat in the demo) **plus** the physics engine internal representation of the corresponding body.

~~To keep track of what physics engine body a DOM element is linked with is not covered, but is manually possible in some cases (as in the demo).~~ If you look at the source code (https://github.com/mikkokam/NUI/blob/master/src/www/nui/ionic/box2d/nui-ionic-box2d.js ) - you see that at init we create some bodies for the bounds (floor and walls) - and later create a body for each DOM element requesting it.

EDIT: I **did** have it covered there:

```
// Circular cross-references... Element into body & body into element for quick access:
fix.userData = {domObj:elem, width:width, height:height};
elem[0].body = body;
```

So you can fetch the body from the DOM element and vice versa.
Any DOM element that has been initialized into the physics engine world, will have a _body_ property referring to the physics engine world body linked with it.

I updated the demo; CLICK AN OBJECT and it will be destroyed from the physics world and from the DOM. So, see the Codepen demo code to see how to do it.

http://codepen.io/mikkokam/pen/Geotz

**Comment by qtagtech** [comment]
Thanks, Amazing library! I hope I'm able to contribute since it is still a bit out of my scope but I'm getting there :+1:

**Comment by mikkokam** [comment]
Thanks!
It is basically a wrapper for Google Liquidfun / a way to connect DOM elements with the Liquidfun engine, using Angular and Ionic's touch events. Would be possible to connect things through vanilla JS (or React or any other view layer DOM lib).

Liquidfun is a bit large, but is based on Box2D, adding _liquids_ and other nice things to it. It would be possible to create awesome physics-based things with it. See demos at http://google.github.io/liquidfun/

For liquids / complex particle systems - or very large amounts of objects, DOM is probably not the way to visualize things, canvas based rendering of the physics engine calculations might be faster.
